# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
      (modulesPath + "/installer/scan/not-detected.nix")
      ./modules/system/btrfs.nix
  ];

  mySystem.btrfs.enable = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Use latest kernel.
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernel.sysctl = { "vm.swappiness" = 10; };
  boot.kernelParams = [
    "zswap.enabled=1" # enables zswap
    "zswap.compressor=zstd" # compression algorithm
    "zswap.max_pool_percent=20" # maximum percentage of RAM that zswap is allowed to use
    "zswap.shrinker_enabled=1" # whether to shrink the pool proactively on high memory pressure
  ];

  # Use the systemd-boot EFI boot loader.
  boot.loader = { 
    efi.canTouchEfiVariables = true;
    systemd-boot = {
      enable = true;
      edk2-uefi-shell.enable = true;
      edk2-uefi-shell.sortKey = "z_edk2";
      extraEntries."linux-mint.conf" = ''
        title  Linux Mint Debian Edition
        efi    /efi/edk2-uefi-shell/shell.efi
        options -nointerrupt -nomap -noversion HD1b:EFI\debian\shimx64.efi
        sort-key y_lmde
      '';
    };  
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA13-9063";
      fsType = "vfat";
      options = [ "umask=0077" "iocharset=ascii" "errors=remount-ro" ];
    };
  
  swapDevices = [{
    device = "/swap/swapfile";
    size = 8*1024;
  }];

  hardware.graphics.extraPackages = with pkgs; [
    rocmPackages.clr.icd
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
